url: http://hazirguo.github.io/demo
baseurl: /hellogithub

#base: /demo

#markdown: rdiscount
permalink: /blog/:year:month:day/:title.html
pygments: true
exclude: ['Rakefile.rb', 'CNAME', 'README.markdown']
